version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "db"
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 9080:8080
  web:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 30s && npm start"
  nginx:
    build: ./nginx/.
    ports:
    - "8080:80"
    depends_on:
      - db
      - web
